name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.detect.outputs.changed_services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false  # ❗ disables default GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install tools dependencies
        run: npm install
        working-directory: ./tools

      - name: Detect changed services
        id: detect
        run: |
          CHANGED=$(node tools/detect-changes.js)
          echo "changed_services=$CHANGED" >> $GITHUB_OUTPUT

  semantic-release:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed_services) }}
    defaults:
      run:
        working-directory: services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false  # ❗ disables default GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git to use GH_TOKEN
        run: |
          git config --global user.name "semantic-release-bot"
          git config --global user.email "semantic-release@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release